LSDAF/lsdaf_client

elements/hud/hud.tscn
elements/hud/settings_button.gd
elements/hud/settings_menu/settings_menu.gd
elements/hud/settings_menu/settings_menu.tscn

https://lsadf.atlassian.net/browse/MFC-69
- Create a settings menu
- Access it with a button
- Add wip buttons for later, and a login button (wip)

feat: add settings menu

---

Makefile
autoload/services/toaster/toaster_service.gd
elements/components/toast/toast.gd
elements/components/toast/toast.tscn
elements/components/toast/toaster.gd
elements/components/toast/toaster.tscn
elements/root/root.gd
elements/root/root.tscn
project.godot

https://lsadf.atlassian.net/browse/MFC-95
- Un `ToasterService` qui permet d'afficher des `Toast` de n'importe où dans l'app
- Les scenes `Toaster` et `Toast` associées

feat: add a toaster service

---

autoload/services/http/api_routes.gd
elements/launcher/launcher.gd
elements/launcher/login_register/login_register.gd
elements/launcher/login_register/login_register.tscn
http/auth/auth_api.gd
models/http/auth/login_response_dto.gd
models/http/auth/register_response_dto.gd

https://lsadf.atlassian.net/browse/MFC-64
- Add a register form
- Allow to toggle between register and login form
- When registered, login the user

feat: can register or login

---

autoload/services/http/api.gd
autoload/services/user_data_service/user_data_service.gd
elements/hud/settings_menu/settings_menu.gd
elements/launcher/launcher.gd
elements/launcher/login_register/login_register.gd
elements/root/root.gd
http/auth/auth_api.gd
http/game_save/game_save_api.gd
http/user/user_api.gd
models/http/auth/register_response_dto.gd
project.godot
resources/user_data/user_data.gd

https://lsadf.atlassian.net/browse/MFC-70

feat: store access token to user files and relogs using it

---

autoload/services/http/api_routes.gd
autoload/services/user_data_service/user_data_service.gd
elements/launcher/launcher.gd
http/auth/auth_api.gd
models/http/auth/login_response_dto.gd
resources/user_data/user_data.gd

https://lsadf.atlassian.net/browse/MFC-96
refresh the login using the refresh token

feat: refresh the login using the refresh token

---

autoload/services/game_save/game_save_service.gd
autoload/services/http/api_routes.gd
autoload/services/user_data_service/user_data_service.gd
elements/hud/settings_menu/nickname_menu/nickname_menu.gd
elements/hud/settings_menu/nickname_menu/nickname_menu.tscn
elements/hud/settings_menu/settings_menu.gd
elements/hud/settings_menu/settings_menu.tscn
http/game_save/game_save_api.gd
http/user/user_api.gd

https://lsadf.atlassian.net/browse/MFC-80
Add a UI to update the game nickname

feat: can update the nickname from the client

---

elements/launcher/game_save.gd
elements/launcher/game_save.tscn
models/http/game_save/game_save_dto.gd

https://lsadf.atlassian.net/browse/MFC-81
Display the nickname of the game on the game save list

feat: see the nickname of the game save

---

elements/root/root.gd

No ticket
Logout now clears the user data

fix: logout now clears the user data

---

addons/gdUnit4/GdUnitRunner.cfg
autoload/data/currencies/currencies.gd
autoload/http/api_routes/api_routes.gd
autoload/services/game_save/game_save_service.gd
elements/game_main/game_main.gd
elements/game_main/game_main.tscn
elements/launcher/game_save.gd
elements/launcher/game_save.tscn
http/game_save/game_save_api.gd
models/http/auth/register_response_dto.gd
models/http/game_save/currencies_dto.gd
models/http/game_save/game_save_dto.gd
project.godot
tests/unit/test_example.gd

https://lsadf.atlassian.net/browse/MFC-71

feat: save currencies to the server (not yet tested)

---

autoload/data/currencies/currencies.gd
autoload/data/stage/stage.gd
autoload/http/api_routes/api_routes.gd
autoload/services/game_save/game_save_service.gd
http/stage/stage_api.gd
models/http/stage/fetch_stage_dto.gd

https://lsadf.atlassian.net/browse/MFC-76

feat: load stage

---

src/autoload/services/services.gd
src/autoload/services/user_local_data_service/user_local_data_service.gd
src/elements/launcher/launcher.gd
src/elements/launcher/login_register/login_register.gd
src/elements/launcher/login_register/login_register.tscn
src/models/user_data/user_data.gd

feat: can remember email when loging in or registering

---

.github/workflows/tests/comment.js

chore: add report log link to pr test comment

---

.github/workflows/tests.yml
.gutconfig.json

chore: update workflow for gut

---

src/autoload/http/api_client/api_client.gd
src/autoload/http/api_routes/api_routes.gd
src/http/auth/auth_api.gd
src/models/http/auth/login_response_dto.gd

Fix the client's consumption of the API
Related to https://github.com/LSDAF/lsdaf_backend/pull/35

fix: update the game to the new api

---

src/resources/items/blueprints/boots/normal/normal_boots_1.tres
src/resources/items/blueprints/boots/normal/normal_boots_2.tres
src/resources/items/blueprints/chestplates/normal/normal_chestplate_1.tres
src/resources/items/blueprints/chestplates/normal/normal_chestplate_2.tres
src/resources/items/blueprints/gloves/normal/normal_gloves_1.tres
src/resources/items/blueprints/gloves/normal/normal_gloves_2.tres
src/resources/items/blueprints/helmets/normal/normal_helmet_1.tres
src/resources/items/blueprints/helmets/normal/normal_helmet_2.tres
src/resources/items/blueprints/shields/normal/normal_shield_1.tres
src/resources/items/blueprints/shields/normal/normal_shield_2.tres
src/resources/items/blueprints/swords/normal/normal_sword_1.tres
src/resources/items/blueprints/swords/normal/normal_sword_2.tres

This reverts commit a2882814e89d047fb6826cee0b7d118d2c222796.
Introduced in https://github.com/LSDAF/lsdaf_client/pull/52

Revert "chore: added .tres files"

---

.github/workflows/tests.yml

fix: update deprecated upload artifact action to v4

---

src/elements/hud/inventory_menu/inventory_item/inventory_item.gd
src/elements/hud/inventory_menu/inventory_item/inventory_item.tscn
src/models/items/item/type/item_type.gd

feat: display item type

---

src/services/user_local_data/__tests__/user_local_data_test.gd

fix: dont save userdata to disk in user local data tests

---

.pre-commit-script.sh
scripts/gdtoolkit.sh
scripts/strict-layers.sh

- Add strict-layers.sh to enforce Data access through Services only
- Add gdtoolkit.sh as a standalone script for formatting and linting
- Update pre-commit script to use both scripts
- Add directory scanning option (-d, --directory) to both scripts

feat: add scripts for architectural constraints

---

.github/actions/setup-venv/action.yml
.github/workflows/code_quality.yml
scripts/gdtoolkit.sh
src/elements/hud/amethyst_label.gd
src/elements/hud/characteristics_menu/characteristics_menu_item/characteristics_menu_item.gd
src/elements/hud/currencies/diamonds_label.gd
src/elements/hud/currencies/gold_label.gd
src/elements/hud/inventory_menu/item_details_menu/item_details_menu.gd
src/elements/mobs/mob/mob.gd
src/elements/player/player.gd
src/services/characteristics/characteristics_service.gd
src/services/currencies/currencies_service.gd

The main goal of this PR was to enforce proper architectural layering by:
1. Moving direct data access from UI and game elements to service classes
2. Adding appropriate getter and update functions in services
3. Ensuring that only service classes can access the data layer
This change improves the codebase architecture by:
- Enforcing better separation of concerns
- Making the code more maintainable
- Reducing coupling between layers
- Making it easier to modify the data layer without affecting UI components

feat: enforce architectural constraints

---

.editorconfig
.windsurfrules
Makefile
src/autoload/http/api_client/api_client.gd
src/autoload/http/api_routes/api_routes.gd
src/http/inventory/inventory_api.gd
src/models/http/inventory/inventory_item_dto.gd
src/models/items/item/item.gd
src/models/items/item/stats/item_stat.gd
src/models/items/item_blueprint/item_blueprint.gd
src/models/items/item_blueprint/pools/__tests__/item_pools_test.gd
src/models/items/item_blueprint/pools/item_pools.gd
src/resources/items/blueprints/boots/normal/normal_boots_1.tres
src/resources/items/blueprints/boots/normal/normal_boots_2.tres
src/resources/items/blueprints/chestplates/normal/normal_chestplate_1.tres
src/resources/items/blueprints/chestplates/normal/normal_chestplate_2.tres
src/resources/items/blueprints/gloves/normal/normal_gloves_1.tres
src/resources/items/blueprints/gloves/normal/normal_gloves_2.tres
src/resources/items/blueprints/helmets/normal/normal_helmet_1.tres
src/resources/items/blueprints/helmets/normal/normal_helmet_2.tres
src/resources/items/blueprints/shields/normal/normal_shield_1.tres
src/resources/items/blueprints/shields/normal/normal_shield_2.tres
src/resources/items/blueprints/swords/normal/normal_sword_1.tres
src/resources/items/blueprints/swords/normal/normal_sword_2.tres
src/services/game_save/__tests__/game_save_service_test.gd
src/services/game_save/game_save_service.gd
src/services/inventory/__tests__/inventory_service_test.gd
src/services/inventory/inventory_service.gd
src/services/items/__tests__/items_service_test.gd
src/services/items/items_service.gd

feat: save the items with the client id
